### ISSUE TITLE
rXjs IE11

### ISSUE THREAD

**Issue by rubenberendsen** [Kentico/kentico-cloud-js#80] opened 2018-11-02 07:51 UTC
Hi,

I'm using this sdk in combination with NuxtJS. 

My project doesn't work in IE11 and i think this is because of rXjs. Can we use this SDK without rXjs?
Our do you have an another solution?

Example: www.frontis.nl

Thanks

**Comment by Enngage** [comment] 2018-11-02 07:59
Hi,

rxjs does support IE 11. Angular, who heavily relies on rxjs states that here: https://angular.io/guide/browser-support 

I think the issue might be with something else. I tried opening your site on my IE and it indeed doesn't work, but I can't read the error because the script is minified. What error do you see in your local dev environment? Are you sure it is caused by this library?

**Comment by Enngage** [comment] 2018-11-02 10:34
Update: I've tried running my sample Angular 5 app with latest version of this sdk and it does work in my IE 11 - can you try this on your end as well - https://kentico-cloud-angular-5-demo.stackblitz.io/ ?

**Comment by rubenberendsen** [comment] 2018-11-05 14:36
Hi,

My colleague has made a new repository with NuxtJS and Kentico Cloud (https://github.com/Domitnator/NuxtKenticoCloudIE11).

We have different pages with en without Kentico Cloud import.

As you can see the pages with Kentico Cloud Import gives an error in IE11. In Chrome it works perfect.

Thank you

**Comment by Domitnator** [comment] 2018-11-05 15:07
Hi Richard,

A little addition to @rubenberendsen his comment.

The repository consist of just a basic nuxtjs project (https://nuxtjs.org/guide/installation)

As you might not be familiar with nuxt:

1. Clone the project: https://github.com/Domitnator/NuxtKenticoCloudIE11.git
2. Run: npm install
3. Run the project: npm run dev

Note that the only difference between the with/without route is the import of kentico-cloud-delivery:

![image](https://user-images.githubusercontent.com/13468638/48005180-0d62b100-e113-11e8-84ed-374a8248553e.png)

**Comment by Enngage** [comment] 2018-11-06 06:55
@Domitnator thank you for the steps!

@rubenberendsen, @Domitnator What should I be looking for exactly? I'm able to switch between views with/without correctly. Though, I do see a syntax error in console. However, I do see this error even on view without the import and even if I remove the import completely from the with/index.vue.

![without_syntax_error](https://user-images.githubusercontent.com/7137351/48047757-637a3780-e199-11e8-9398-3e20883ff3e4.png)

**Comment by Enngage** [comment] 2018-11-06 07:37
Additionally, I also tried loading data using the SDK with this code:

```
 <h3>Items</h3>
      <ul>
        <li v-for="item in items">
          {{ item.system.codename }}
        </li>
      </ul>
```

```
<script>
import Logo from '~/components/Logo.vue'
import { ContentItem, Fields, TypeResolver, DeliveryClient } from 'kentico-cloud-delivery'; 

const deliveryClient = new DeliveryClient({
  projectId: 'da5abe9f-fdad-4168-97cd-b3464be2ccb9'
});

export default {
  components: {
    Logo
  },
  asyncData({env}){
    return deliveryClient.items().getPromise().then(response => {
      console.log(response);
     return { items: response.items};
    });
  }
}
</script>
```
And that seems to work in IE as well:

![ie_sdk](https://user-images.githubusercontent.com/7137351/48049495-26b13f00-e19f-11e8-986d-07efa2b42d20.gif)

**Comment by Enngage** [comment] 2018-11-14 11:02
Is there any update on this?

**Comment by rubenberendsen** [comment] 2018-11-16 12:38
Yes this will work, but the error in the console is our problem. 
Because of that error, other javascript doesn't load correctly and the site is broken.
The get from Kentico Cloud works fine, that's not the problem.

**Comment by Enngage** [comment] 2018-11-16 13:19
But I get that console error regardless of whether I import js sdk, so how is the error related to it?

**Comment by Enngage** [comment] 2018-11-22 13:35
Closing for now, but feel free to reopen if you are able to isolate the error with js sdk

**Closed by Enngage** 2018-11-22 13:35 UTC
